sad_words = [
    "sad",
    "unhappy",
    "depressed",
    "miserable",
    "heartbroken",
    "lonely",
    "hopeless",
    "gloomy",
    "melancholy",
    "grief",
    "sorrow",
    "regret",
    "disappointed",
    "discouraged",
    "hurt",
    "crying",
    "tears",
    "despair",
    "isolated",
    "downcast",
    "anxious",
    "overwhelmed",
    "tired",
    "lost",
    "abandoned",
    "broken",
    "failure",
    "worthless",
    "rejected",
    "empty"
]

starter_encouragement = [
    "You are capable of more than you think.",
    "Every small step forward still counts.",
    "Progress takes time, and you are making it.",
    "Mistakes are proof that you are trying.",
    "You have overcome challenges before, you can do it again.",
    "Your effort today builds your strength for tomorrow.",
    "Keep going, even if it feels slow.",
    "You are learning and growing every day.",
    "Hard moments do not last forever.",
    "Believe in your ability to improve.",
    "Stay patient with yourself.",
    "You are stronger than your doubts.",
    "Success starts with persistence.",
    "Keep showing up for yourself.",
    "You are moving in the right direction."
]
